DICE1='/home/gustavo/Dropbox/PythonScripts/game_test/src/pictures/dice_1.png'
DICE2='/home/gustavo/Dropbox/PythonScripts/game_test/src/pictures/dice_2.png'
DICE3='/home/gustavo/Dropbox/PythonScripts/game_test/src/pictures/dice_3.png'
DICE4='/home/gustavo/Dropbox/PythonScripts/game_test/src/pictures/dice_4.png'
DICE5='/home/gustavo/Dropbox/PythonScripts/game_test/src/pictures/dice_5.png'
DICE6='/home/gustavo/Dropbox/PythonScripts/game_test/src/pictures/dice_6.png'